title: Academic # Website name
baseURL: 'https://example.com/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-core
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-seo
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, wowchemycms_config]
  section: [HTML, RSS]
  page: [HTML, RSS]
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
  wowchemycms_config:
    baseName: cms
    isPlainText: true
    mediaType: application/json
    notAlternative: true
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
  exif:
    disableDate: true
    disableLatLong: true
  config:
    JPEG:
      quality: 75
    PNG:
      compression: 9
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
security:
  enableInlineShortcodes: false
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  funcs:
    getenv: ['^HUGO_', '^WC_']
  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']
sitemap:
  _merge: deep 