[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  GO_VERSION = "1.19"
  HUGO_VERSION = "0.101.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/dotcyril"
  status = 301
  force = true